#ifndef _ALTERA_CPUID_REGBRIDGE_H_
#define _ALTERA_CPUID_REGBRIDGE_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'CPUID_RegBridge' and devices
 * connected to the following master:
 *   m0
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'ID_PFR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_PFR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_PFR0_COMPONENT_TYPE altera_avalon_pio
#define ID_PFR0_COMPONENT_NAME ID_PFR0
#define ID_PFR0_BASE 0x0
#define ID_PFR0_SPAN 16
#define ID_PFR0_END 0xf
#define ID_PFR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_PFR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_PFR0_CAPTURE 0
#define ID_PFR0_DATA_WIDTH 32
#define ID_PFR0_DO_TEST_BENCH_WIRING 0
#define ID_PFR0_DRIVEN_SIM_VALUE 0
#define ID_PFR0_EDGE_TYPE NONE
#define ID_PFR0_FREQ 50000000
#define ID_PFR0_HAS_IN 0
#define ID_PFR0_HAS_OUT 1
#define ID_PFR0_HAS_TRI 0
#define ID_PFR0_IRQ_TYPE NONE
#define ID_PFR0_RESET_VALUE 0

/*
 * Macros for device 'ID_PFR1', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_PFR1_'.
 * The prefix is the slave descriptor.
 */
#define ID_PFR1_COMPONENT_TYPE altera_avalon_pio
#define ID_PFR1_COMPONENT_NAME ID_PFR1
#define ID_PFR1_BASE 0x10
#define ID_PFR1_SPAN 16
#define ID_PFR1_END 0x1f
#define ID_PFR1_BIT_CLEARING_EDGE_REGISTER 0
#define ID_PFR1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_PFR1_CAPTURE 0
#define ID_PFR1_DATA_WIDTH 32
#define ID_PFR1_DO_TEST_BENCH_WIRING 0
#define ID_PFR1_DRIVEN_SIM_VALUE 0
#define ID_PFR1_EDGE_TYPE NONE
#define ID_PFR1_FREQ 50000000
#define ID_PFR1_HAS_IN 0
#define ID_PFR1_HAS_OUT 1
#define ID_PFR1_HAS_TRI 0
#define ID_PFR1_IRQ_TYPE NONE
#define ID_PFR1_RESET_VALUE 0

/*
 * Macros for device 'ID_DFR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_DFR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_DFR0_COMPONENT_TYPE altera_avalon_pio
#define ID_DFR0_COMPONENT_NAME ID_DFR0
#define ID_DFR0_BASE 0x20
#define ID_DFR0_SPAN 16
#define ID_DFR0_END 0x2f
#define ID_DFR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_DFR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_DFR0_CAPTURE 0
#define ID_DFR0_DATA_WIDTH 32
#define ID_DFR0_DO_TEST_BENCH_WIRING 0
#define ID_DFR0_DRIVEN_SIM_VALUE 0
#define ID_DFR0_EDGE_TYPE NONE
#define ID_DFR0_FREQ 50000000
#define ID_DFR0_HAS_IN 0
#define ID_DFR0_HAS_OUT 1
#define ID_DFR0_HAS_TRI 0
#define ID_DFR0_IRQ_TYPE NONE
#define ID_DFR0_RESET_VALUE 0

/*
 * Macros for device 'ID_AFR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_AFR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_AFR0_COMPONENT_TYPE altera_avalon_pio
#define ID_AFR0_COMPONENT_NAME ID_AFR0
#define ID_AFR0_BASE 0x30
#define ID_AFR0_SPAN 16
#define ID_AFR0_END 0x3f
#define ID_AFR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_AFR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_AFR0_CAPTURE 0
#define ID_AFR0_DATA_WIDTH 32
#define ID_AFR0_DO_TEST_BENCH_WIRING 0
#define ID_AFR0_DRIVEN_SIM_VALUE 0
#define ID_AFR0_EDGE_TYPE NONE
#define ID_AFR0_FREQ 50000000
#define ID_AFR0_HAS_IN 0
#define ID_AFR0_HAS_OUT 1
#define ID_AFR0_HAS_TRI 0
#define ID_AFR0_IRQ_TYPE NONE
#define ID_AFR0_RESET_VALUE 0

/*
 * Macros for device 'ID_MMFR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_MMFR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_MMFR0_COMPONENT_TYPE altera_avalon_pio
#define ID_MMFR0_COMPONENT_NAME ID_MMFR0
#define ID_MMFR0_BASE 0x40
#define ID_MMFR0_SPAN 16
#define ID_MMFR0_END 0x4f
#define ID_MMFR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_MMFR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_MMFR0_CAPTURE 0
#define ID_MMFR0_DATA_WIDTH 32
#define ID_MMFR0_DO_TEST_BENCH_WIRING 0
#define ID_MMFR0_DRIVEN_SIM_VALUE 0
#define ID_MMFR0_EDGE_TYPE NONE
#define ID_MMFR0_FREQ 50000000
#define ID_MMFR0_HAS_IN 0
#define ID_MMFR0_HAS_OUT 1
#define ID_MMFR0_HAS_TRI 0
#define ID_MMFR0_IRQ_TYPE NONE
#define ID_MMFR0_RESET_VALUE 0

/*
 * Macros for device 'ID_MMFR1', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_MMFR1_'.
 * The prefix is the slave descriptor.
 */
#define ID_MMFR1_COMPONENT_TYPE altera_avalon_pio
#define ID_MMFR1_COMPONENT_NAME ID_MMFR1
#define ID_MMFR1_BASE 0x50
#define ID_MMFR1_SPAN 16
#define ID_MMFR1_END 0x5f
#define ID_MMFR1_BIT_CLEARING_EDGE_REGISTER 0
#define ID_MMFR1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_MMFR1_CAPTURE 0
#define ID_MMFR1_DATA_WIDTH 32
#define ID_MMFR1_DO_TEST_BENCH_WIRING 0
#define ID_MMFR1_DRIVEN_SIM_VALUE 0
#define ID_MMFR1_EDGE_TYPE NONE
#define ID_MMFR1_FREQ 50000000
#define ID_MMFR1_HAS_IN 0
#define ID_MMFR1_HAS_OUT 1
#define ID_MMFR1_HAS_TRI 0
#define ID_MMFR1_IRQ_TYPE NONE
#define ID_MMFR1_RESET_VALUE 0

/*
 * Macros for device 'ID_MMFR2', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_MMFR2_'.
 * The prefix is the slave descriptor.
 */
#define ID_MMFR2_COMPONENT_TYPE altera_avalon_pio
#define ID_MMFR2_COMPONENT_NAME ID_MMFR2
#define ID_MMFR2_BASE 0x60
#define ID_MMFR2_SPAN 16
#define ID_MMFR2_END 0x6f
#define ID_MMFR2_BIT_CLEARING_EDGE_REGISTER 0
#define ID_MMFR2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_MMFR2_CAPTURE 0
#define ID_MMFR2_DATA_WIDTH 32
#define ID_MMFR2_DO_TEST_BENCH_WIRING 0
#define ID_MMFR2_DRIVEN_SIM_VALUE 0
#define ID_MMFR2_EDGE_TYPE NONE
#define ID_MMFR2_FREQ 50000000
#define ID_MMFR2_HAS_IN 0
#define ID_MMFR2_HAS_OUT 1
#define ID_MMFR2_HAS_TRI 0
#define ID_MMFR2_IRQ_TYPE NONE
#define ID_MMFR2_RESET_VALUE 0

/*
 * Macros for device 'ID_MMFR3', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_MMFR3_'.
 * The prefix is the slave descriptor.
 */
#define ID_MMFR3_COMPONENT_TYPE altera_avalon_pio
#define ID_MMFR3_COMPONENT_NAME ID_MMFR3
#define ID_MMFR3_BASE 0x70
#define ID_MMFR3_SPAN 16
#define ID_MMFR3_END 0x7f
#define ID_MMFR3_BIT_CLEARING_EDGE_REGISTER 0
#define ID_MMFR3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_MMFR3_CAPTURE 0
#define ID_MMFR3_DATA_WIDTH 32
#define ID_MMFR3_DO_TEST_BENCH_WIRING 0
#define ID_MMFR3_DRIVEN_SIM_VALUE 0
#define ID_MMFR3_EDGE_TYPE NONE
#define ID_MMFR3_FREQ 50000000
#define ID_MMFR3_HAS_IN 0
#define ID_MMFR3_HAS_OUT 1
#define ID_MMFR3_HAS_TRI 0
#define ID_MMFR3_IRQ_TYPE NONE
#define ID_MMFR3_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR0_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR0_COMPONENT_NAME ID_ISAR0
#define ID_ISAR0_BASE 0x80
#define ID_ISAR0_SPAN 16
#define ID_ISAR0_END 0x8f
#define ID_ISAR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR0_CAPTURE 0
#define ID_ISAR0_DATA_WIDTH 32
#define ID_ISAR0_DO_TEST_BENCH_WIRING 0
#define ID_ISAR0_DRIVEN_SIM_VALUE 0
#define ID_ISAR0_EDGE_TYPE NONE
#define ID_ISAR0_FREQ 50000000
#define ID_ISAR0_HAS_IN 0
#define ID_ISAR0_HAS_OUT 1
#define ID_ISAR0_HAS_TRI 0
#define ID_ISAR0_IRQ_TYPE NONE
#define ID_ISAR0_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR1', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR1_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR1_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR1_COMPONENT_NAME ID_ISAR1
#define ID_ISAR1_BASE 0x90
#define ID_ISAR1_SPAN 16
#define ID_ISAR1_END 0x9f
#define ID_ISAR1_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR1_CAPTURE 0
#define ID_ISAR1_DATA_WIDTH 32
#define ID_ISAR1_DO_TEST_BENCH_WIRING 0
#define ID_ISAR1_DRIVEN_SIM_VALUE 0
#define ID_ISAR1_EDGE_TYPE NONE
#define ID_ISAR1_FREQ 50000000
#define ID_ISAR1_HAS_IN 0
#define ID_ISAR1_HAS_OUT 1
#define ID_ISAR1_HAS_TRI 0
#define ID_ISAR1_IRQ_TYPE NONE
#define ID_ISAR1_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR2', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR2_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR2_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR2_COMPONENT_NAME ID_ISAR2
#define ID_ISAR2_BASE 0xa0
#define ID_ISAR2_SPAN 16
#define ID_ISAR2_END 0xaf
#define ID_ISAR2_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR2_CAPTURE 0
#define ID_ISAR2_DATA_WIDTH 32
#define ID_ISAR2_DO_TEST_BENCH_WIRING 0
#define ID_ISAR2_DRIVEN_SIM_VALUE 0
#define ID_ISAR2_EDGE_TYPE NONE
#define ID_ISAR2_FREQ 50000000
#define ID_ISAR2_HAS_IN 0
#define ID_ISAR2_HAS_OUT 1
#define ID_ISAR2_HAS_TRI 0
#define ID_ISAR2_IRQ_TYPE NONE
#define ID_ISAR2_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR3', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR3_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR3_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR3_COMPONENT_NAME ID_ISAR3
#define ID_ISAR3_BASE 0xb0
#define ID_ISAR3_SPAN 16
#define ID_ISAR3_END 0xbf
#define ID_ISAR3_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR3_CAPTURE 0
#define ID_ISAR3_DATA_WIDTH 32
#define ID_ISAR3_DO_TEST_BENCH_WIRING 0
#define ID_ISAR3_DRIVEN_SIM_VALUE 0
#define ID_ISAR3_EDGE_TYPE NONE
#define ID_ISAR3_FREQ 50000000
#define ID_ISAR3_HAS_IN 0
#define ID_ISAR3_HAS_OUT 1
#define ID_ISAR3_HAS_TRI 0
#define ID_ISAR3_IRQ_TYPE NONE
#define ID_ISAR3_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR4', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR4_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR4_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR4_COMPONENT_NAME ID_ISAR4
#define ID_ISAR4_BASE 0xc0
#define ID_ISAR4_SPAN 16
#define ID_ISAR4_END 0xcf
#define ID_ISAR4_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR4_CAPTURE 0
#define ID_ISAR4_DATA_WIDTH 32
#define ID_ISAR4_DO_TEST_BENCH_WIRING 0
#define ID_ISAR4_DRIVEN_SIM_VALUE 0
#define ID_ISAR4_EDGE_TYPE NONE
#define ID_ISAR4_FREQ 50000000
#define ID_ISAR4_HAS_IN 0
#define ID_ISAR4_HAS_OUT 1
#define ID_ISAR4_HAS_TRI 0
#define ID_ISAR4_IRQ_TYPE NONE
#define ID_ISAR4_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR5', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR5_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR5_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR5_COMPONENT_NAME ID_ISAR5
#define ID_ISAR5_BASE 0xd0
#define ID_ISAR5_SPAN 16
#define ID_ISAR5_END 0xdf
#define ID_ISAR5_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR5_CAPTURE 0
#define ID_ISAR5_DATA_WIDTH 32
#define ID_ISAR5_DO_TEST_BENCH_WIRING 0
#define ID_ISAR5_DRIVEN_SIM_VALUE 0
#define ID_ISAR5_EDGE_TYPE NONE
#define ID_ISAR5_FREQ 50000000
#define ID_ISAR5_HAS_IN 0
#define ID_ISAR5_HAS_OUT 1
#define ID_ISAR5_HAS_TRI 0
#define ID_ISAR5_IRQ_TYPE NONE
#define ID_ISAR5_RESET_VALUE 0

/*
 * Macros for device 'ID_RES0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_RES0_'.
 * The prefix is the slave descriptor.
 */
#define ID_RES0_COMPONENT_TYPE altera_avalon_pio
#define ID_RES0_COMPONENT_NAME ID_RES0
#define ID_RES0_BASE 0xe0
#define ID_RES0_SPAN 16
#define ID_RES0_END 0xef
#define ID_RES0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_RES0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_RES0_CAPTURE 0
#define ID_RES0_DATA_WIDTH 32
#define ID_RES0_DO_TEST_BENCH_WIRING 0
#define ID_RES0_DRIVEN_SIM_VALUE 0
#define ID_RES0_EDGE_TYPE NONE
#define ID_RES0_FREQ 50000000
#define ID_RES0_HAS_IN 0
#define ID_RES0_HAS_OUT 1
#define ID_RES0_HAS_TRI 0
#define ID_RES0_IRQ_TYPE NONE
#define ID_RES0_RESET_VALUE 0

/*
 * Macros for device 'ID_RES1', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_RES1_'.
 * The prefix is the slave descriptor.
 */
#define ID_RES1_COMPONENT_TYPE altera_avalon_pio
#define ID_RES1_COMPONENT_NAME ID_RES1
#define ID_RES1_BASE 0xf0
#define ID_RES1_SPAN 16
#define ID_RES1_END 0xff
#define ID_RES1_BIT_CLEARING_EDGE_REGISTER 0
#define ID_RES1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_RES1_CAPTURE 0
#define ID_RES1_DATA_WIDTH 32
#define ID_RES1_DO_TEST_BENCH_WIRING 0
#define ID_RES1_DRIVEN_SIM_VALUE 0
#define ID_RES1_EDGE_TYPE NONE
#define ID_RES1_FREQ 50000000
#define ID_RES1_HAS_IN 0
#define ID_RES1_HAS_OUT 1
#define ID_RES1_HAS_TRI 0
#define ID_RES1_IRQ_TYPE NONE
#define ID_RES1_RESET_VALUE 0


#endif /* _ALTERA_CPUID_REGBRIDGE_H_ */
