#ifndef _ALTERA_CPUID_REGBRIDGE_H_
#define _ALTERA_CPUID_REGBRIDGE_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file './soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'CPUID_RegBridge' and devices
 * connected to the following master:
 *   m0
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'MIDR', class 'altera_avalon_pio'
 * The macros are prefixed with 'MIDR_'.
 * The prefix is the slave descriptor.
 */
#define MIDR_COMPONENT_TYPE altera_avalon_pio
#define MIDR_COMPONENT_NAME MIDR
#define MIDR_BASE 0x0
#define MIDR_SPAN 16
#define MIDR_END 0xf
#define MIDR_BIT_CLEARING_EDGE_REGISTER 0
#define MIDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MIDR_CAPTURE 0
#define MIDR_DATA_WIDTH 32
#define MIDR_DO_TEST_BENCH_WIRING 0
#define MIDR_DRIVEN_SIM_VALUE 0
#define MIDR_EDGE_TYPE NONE
#define MIDR_FREQ 50000000
#define MIDR_HAS_IN 0
#define MIDR_HAS_OUT 1
#define MIDR_HAS_TRI 0
#define MIDR_IRQ_TYPE NONE
#define MIDR_RESET_VALUE 0

/*
 * Macros for device 'CTR', class 'altera_avalon_pio'
 * The macros are prefixed with 'CTR_'.
 * The prefix is the slave descriptor.
 */
#define CTR_COMPONENT_TYPE altera_avalon_pio
#define CTR_COMPONENT_NAME CTR
#define CTR_BASE 0x10
#define CTR_SPAN 16
#define CTR_END 0x1f
#define CTR_BIT_CLEARING_EDGE_REGISTER 0
#define CTR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CTR_CAPTURE 0
#define CTR_DATA_WIDTH 32
#define CTR_DO_TEST_BENCH_WIRING 0
#define CTR_DRIVEN_SIM_VALUE 0
#define CTR_EDGE_TYPE NONE
#define CTR_FREQ 50000000
#define CTR_HAS_IN 0
#define CTR_HAS_OUT 1
#define CTR_HAS_TRI 0
#define CTR_IRQ_TYPE NONE
#define CTR_RESET_VALUE 0

/*
 * Macros for device 'TCMTR', class 'altera_avalon_pio'
 * The macros are prefixed with 'TCMTR_'.
 * The prefix is the slave descriptor.
 */
#define TCMTR_COMPONENT_TYPE altera_avalon_pio
#define TCMTR_COMPONENT_NAME TCMTR
#define TCMTR_BASE 0x20
#define TCMTR_SPAN 16
#define TCMTR_END 0x2f
#define TCMTR_BIT_CLEARING_EDGE_REGISTER 0
#define TCMTR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TCMTR_CAPTURE 0
#define TCMTR_DATA_WIDTH 32
#define TCMTR_DO_TEST_BENCH_WIRING 0
#define TCMTR_DRIVEN_SIM_VALUE 0
#define TCMTR_EDGE_TYPE NONE
#define TCMTR_FREQ 50000000
#define TCMTR_HAS_IN 0
#define TCMTR_HAS_OUT 1
#define TCMTR_HAS_TRI 0
#define TCMTR_IRQ_TYPE NONE
#define TCMTR_RESET_VALUE 0

/*
 * Macros for device 'TLBTR', class 'altera_avalon_pio'
 * The macros are prefixed with 'TLBTR_'.
 * The prefix is the slave descriptor.
 */
#define TLBTR_COMPONENT_TYPE altera_avalon_pio
#define TLBTR_COMPONENT_NAME TLBTR
#define TLBTR_BASE 0x30
#define TLBTR_SPAN 16
#define TLBTR_END 0x3f
#define TLBTR_BIT_CLEARING_EDGE_REGISTER 0
#define TLBTR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define TLBTR_CAPTURE 0
#define TLBTR_DATA_WIDTH 32
#define TLBTR_DO_TEST_BENCH_WIRING 0
#define TLBTR_DRIVEN_SIM_VALUE 0
#define TLBTR_EDGE_TYPE NONE
#define TLBTR_FREQ 50000000
#define TLBTR_HAS_IN 0
#define TLBTR_HAS_OUT 1
#define TLBTR_HAS_TRI 0
#define TLBTR_IRQ_TYPE NONE
#define TLBTR_RESET_VALUE 0

/*
 * Macros for device 'MPIDR', class 'altera_avalon_pio'
 * The macros are prefixed with 'MPIDR_'.
 * The prefix is the slave descriptor.
 */
#define MPIDR_COMPONENT_TYPE altera_avalon_pio
#define MPIDR_COMPONENT_NAME MPIDR
#define MPIDR_BASE 0x40
#define MPIDR_SPAN 16
#define MPIDR_END 0x4f
#define MPIDR_BIT_CLEARING_EDGE_REGISTER 0
#define MPIDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define MPIDR_CAPTURE 0
#define MPIDR_DATA_WIDTH 32
#define MPIDR_DO_TEST_BENCH_WIRING 0
#define MPIDR_DRIVEN_SIM_VALUE 0
#define MPIDR_EDGE_TYPE NONE
#define MPIDR_FREQ 50000000
#define MPIDR_HAS_IN 0
#define MPIDR_HAS_OUT 1
#define MPIDR_HAS_TRI 0
#define MPIDR_IRQ_TYPE NONE
#define MPIDR_RESET_VALUE 0

/*
 * Macros for device 'REVIDR', class 'altera_avalon_pio'
 * The macros are prefixed with 'REVIDR_'.
 * The prefix is the slave descriptor.
 */
#define REVIDR_COMPONENT_TYPE altera_avalon_pio
#define REVIDR_COMPONENT_NAME REVIDR
#define REVIDR_BASE 0x50
#define REVIDR_SPAN 16
#define REVIDR_END 0x5f
#define REVIDR_BIT_CLEARING_EDGE_REGISTER 0
#define REVIDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define REVIDR_CAPTURE 0
#define REVIDR_DATA_WIDTH 32
#define REVIDR_DO_TEST_BENCH_WIRING 0
#define REVIDR_DRIVEN_SIM_VALUE 0
#define REVIDR_EDGE_TYPE NONE
#define REVIDR_FREQ 50000000
#define REVIDR_HAS_IN 0
#define REVIDR_HAS_OUT 1
#define REVIDR_HAS_TRI 0
#define REVIDR_IRQ_TYPE NONE
#define REVIDR_RESET_VALUE 0

/*
 * Macros for device 'ID_PFR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_PFR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_PFR0_COMPONENT_TYPE altera_avalon_pio
#define ID_PFR0_COMPONENT_NAME ID_PFR0
#define ID_PFR0_BASE 0x60
#define ID_PFR0_SPAN 16
#define ID_PFR0_END 0x6f
#define ID_PFR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_PFR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_PFR0_CAPTURE 0
#define ID_PFR0_DATA_WIDTH 32
#define ID_PFR0_DO_TEST_BENCH_WIRING 0
#define ID_PFR0_DRIVEN_SIM_VALUE 0
#define ID_PFR0_EDGE_TYPE NONE
#define ID_PFR0_FREQ 50000000
#define ID_PFR0_HAS_IN 0
#define ID_PFR0_HAS_OUT 1
#define ID_PFR0_HAS_TRI 0
#define ID_PFR0_IRQ_TYPE NONE
#define ID_PFR0_RESET_VALUE 0

/*
 * Macros for device 'ID_PFR1', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_PFR1_'.
 * The prefix is the slave descriptor.
 */
#define ID_PFR1_COMPONENT_TYPE altera_avalon_pio
#define ID_PFR1_COMPONENT_NAME ID_PFR1
#define ID_PFR1_BASE 0x70
#define ID_PFR1_SPAN 16
#define ID_PFR1_END 0x7f
#define ID_PFR1_BIT_CLEARING_EDGE_REGISTER 0
#define ID_PFR1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_PFR1_CAPTURE 0
#define ID_PFR1_DATA_WIDTH 32
#define ID_PFR1_DO_TEST_BENCH_WIRING 0
#define ID_PFR1_DRIVEN_SIM_VALUE 0
#define ID_PFR1_EDGE_TYPE NONE
#define ID_PFR1_FREQ 50000000
#define ID_PFR1_HAS_IN 0
#define ID_PFR1_HAS_OUT 1
#define ID_PFR1_HAS_TRI 0
#define ID_PFR1_IRQ_TYPE NONE
#define ID_PFR1_RESET_VALUE 0

/*
 * Macros for device 'ID_DFR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_DFR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_DFR0_COMPONENT_TYPE altera_avalon_pio
#define ID_DFR0_COMPONENT_NAME ID_DFR0
#define ID_DFR0_BASE 0x80
#define ID_DFR0_SPAN 16
#define ID_DFR0_END 0x8f
#define ID_DFR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_DFR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_DFR0_CAPTURE 0
#define ID_DFR0_DATA_WIDTH 32
#define ID_DFR0_DO_TEST_BENCH_WIRING 0
#define ID_DFR0_DRIVEN_SIM_VALUE 0
#define ID_DFR0_EDGE_TYPE NONE
#define ID_DFR0_FREQ 50000000
#define ID_DFR0_HAS_IN 0
#define ID_DFR0_HAS_OUT 1
#define ID_DFR0_HAS_TRI 0
#define ID_DFR0_IRQ_TYPE NONE
#define ID_DFR0_RESET_VALUE 0

/*
 * Macros for device 'ID_AFR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_AFR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_AFR0_COMPONENT_TYPE altera_avalon_pio
#define ID_AFR0_COMPONENT_NAME ID_AFR0
#define ID_AFR0_BASE 0x90
#define ID_AFR0_SPAN 16
#define ID_AFR0_END 0x9f
#define ID_AFR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_AFR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_AFR0_CAPTURE 0
#define ID_AFR0_DATA_WIDTH 32
#define ID_AFR0_DO_TEST_BENCH_WIRING 0
#define ID_AFR0_DRIVEN_SIM_VALUE 0
#define ID_AFR0_EDGE_TYPE NONE
#define ID_AFR0_FREQ 50000000
#define ID_AFR0_HAS_IN 0
#define ID_AFR0_HAS_OUT 1
#define ID_AFR0_HAS_TRI 0
#define ID_AFR0_IRQ_TYPE NONE
#define ID_AFR0_RESET_VALUE 0

/*
 * Macros for device 'ID_MMFR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_MMFR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_MMFR0_COMPONENT_TYPE altera_avalon_pio
#define ID_MMFR0_COMPONENT_NAME ID_MMFR0
#define ID_MMFR0_BASE 0xa0
#define ID_MMFR0_SPAN 16
#define ID_MMFR0_END 0xaf
#define ID_MMFR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_MMFR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_MMFR0_CAPTURE 0
#define ID_MMFR0_DATA_WIDTH 32
#define ID_MMFR0_DO_TEST_BENCH_WIRING 0
#define ID_MMFR0_DRIVEN_SIM_VALUE 0
#define ID_MMFR0_EDGE_TYPE NONE
#define ID_MMFR0_FREQ 50000000
#define ID_MMFR0_HAS_IN 0
#define ID_MMFR0_HAS_OUT 1
#define ID_MMFR0_HAS_TRI 0
#define ID_MMFR0_IRQ_TYPE NONE
#define ID_MMFR0_RESET_VALUE 0

/*
 * Macros for device 'ID_MMFR1', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_MMFR1_'.
 * The prefix is the slave descriptor.
 */
#define ID_MMFR1_COMPONENT_TYPE altera_avalon_pio
#define ID_MMFR1_COMPONENT_NAME ID_MMFR1
#define ID_MMFR1_BASE 0xb0
#define ID_MMFR1_SPAN 16
#define ID_MMFR1_END 0xbf
#define ID_MMFR1_BIT_CLEARING_EDGE_REGISTER 0
#define ID_MMFR1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_MMFR1_CAPTURE 0
#define ID_MMFR1_DATA_WIDTH 32
#define ID_MMFR1_DO_TEST_BENCH_WIRING 0
#define ID_MMFR1_DRIVEN_SIM_VALUE 0
#define ID_MMFR1_EDGE_TYPE NONE
#define ID_MMFR1_FREQ 50000000
#define ID_MMFR1_HAS_IN 0
#define ID_MMFR1_HAS_OUT 1
#define ID_MMFR1_HAS_TRI 0
#define ID_MMFR1_IRQ_TYPE NONE
#define ID_MMFR1_RESET_VALUE 0

/*
 * Macros for device 'ID_MMFR2', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_MMFR2_'.
 * The prefix is the slave descriptor.
 */
#define ID_MMFR2_COMPONENT_TYPE altera_avalon_pio
#define ID_MMFR2_COMPONENT_NAME ID_MMFR2
#define ID_MMFR2_BASE 0xc0
#define ID_MMFR2_SPAN 16
#define ID_MMFR2_END 0xcf
#define ID_MMFR2_BIT_CLEARING_EDGE_REGISTER 0
#define ID_MMFR2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_MMFR2_CAPTURE 0
#define ID_MMFR2_DATA_WIDTH 32
#define ID_MMFR2_DO_TEST_BENCH_WIRING 0
#define ID_MMFR2_DRIVEN_SIM_VALUE 0
#define ID_MMFR2_EDGE_TYPE NONE
#define ID_MMFR2_FREQ 50000000
#define ID_MMFR2_HAS_IN 0
#define ID_MMFR2_HAS_OUT 1
#define ID_MMFR2_HAS_TRI 0
#define ID_MMFR2_IRQ_TYPE NONE
#define ID_MMFR2_RESET_VALUE 0

/*
 * Macros for device 'ID_MMFR3', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_MMFR3_'.
 * The prefix is the slave descriptor.
 */
#define ID_MMFR3_COMPONENT_TYPE altera_avalon_pio
#define ID_MMFR3_COMPONENT_NAME ID_MMFR3
#define ID_MMFR3_BASE 0xd0
#define ID_MMFR3_SPAN 16
#define ID_MMFR3_END 0xdf
#define ID_MMFR3_BIT_CLEARING_EDGE_REGISTER 0
#define ID_MMFR3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_MMFR3_CAPTURE 0
#define ID_MMFR3_DATA_WIDTH 32
#define ID_MMFR3_DO_TEST_BENCH_WIRING 0
#define ID_MMFR3_DRIVEN_SIM_VALUE 0
#define ID_MMFR3_EDGE_TYPE NONE
#define ID_MMFR3_FREQ 50000000
#define ID_MMFR3_HAS_IN 0
#define ID_MMFR3_HAS_OUT 1
#define ID_MMFR3_HAS_TRI 0
#define ID_MMFR3_IRQ_TYPE NONE
#define ID_MMFR3_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR0', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR0_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR0_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR0_COMPONENT_NAME ID_ISAR0
#define ID_ISAR0_BASE 0xe0
#define ID_ISAR0_SPAN 16
#define ID_ISAR0_END 0xef
#define ID_ISAR0_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR0_CAPTURE 0
#define ID_ISAR0_DATA_WIDTH 32
#define ID_ISAR0_DO_TEST_BENCH_WIRING 0
#define ID_ISAR0_DRIVEN_SIM_VALUE 0
#define ID_ISAR0_EDGE_TYPE NONE
#define ID_ISAR0_FREQ 50000000
#define ID_ISAR0_HAS_IN 0
#define ID_ISAR0_HAS_OUT 1
#define ID_ISAR0_HAS_TRI 0
#define ID_ISAR0_IRQ_TYPE NONE
#define ID_ISAR0_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR1', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR1_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR1_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR1_COMPONENT_NAME ID_ISAR1
#define ID_ISAR1_BASE 0xf0
#define ID_ISAR1_SPAN 16
#define ID_ISAR1_END 0xff
#define ID_ISAR1_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR1_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR1_CAPTURE 0
#define ID_ISAR1_DATA_WIDTH 32
#define ID_ISAR1_DO_TEST_BENCH_WIRING 0
#define ID_ISAR1_DRIVEN_SIM_VALUE 0
#define ID_ISAR1_EDGE_TYPE NONE
#define ID_ISAR1_FREQ 50000000
#define ID_ISAR1_HAS_IN 0
#define ID_ISAR1_HAS_OUT 1
#define ID_ISAR1_HAS_TRI 0
#define ID_ISAR1_IRQ_TYPE NONE
#define ID_ISAR1_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR2', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR2_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR2_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR2_COMPONENT_NAME ID_ISAR2
#define ID_ISAR2_BASE 0x100
#define ID_ISAR2_SPAN 16
#define ID_ISAR2_END 0x10f
#define ID_ISAR2_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR2_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR2_CAPTURE 0
#define ID_ISAR2_DATA_WIDTH 32
#define ID_ISAR2_DO_TEST_BENCH_WIRING 0
#define ID_ISAR2_DRIVEN_SIM_VALUE 0
#define ID_ISAR2_EDGE_TYPE NONE
#define ID_ISAR2_FREQ 50000000
#define ID_ISAR2_HAS_IN 0
#define ID_ISAR2_HAS_OUT 1
#define ID_ISAR2_HAS_TRI 0
#define ID_ISAR2_IRQ_TYPE NONE
#define ID_ISAR2_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR3', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR3_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR3_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR3_COMPONENT_NAME ID_ISAR3
#define ID_ISAR3_BASE 0x110
#define ID_ISAR3_SPAN 16
#define ID_ISAR3_END 0x11f
#define ID_ISAR3_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR3_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR3_CAPTURE 0
#define ID_ISAR3_DATA_WIDTH 32
#define ID_ISAR3_DO_TEST_BENCH_WIRING 0
#define ID_ISAR3_DRIVEN_SIM_VALUE 0
#define ID_ISAR3_EDGE_TYPE NONE
#define ID_ISAR3_FREQ 50000000
#define ID_ISAR3_HAS_IN 0
#define ID_ISAR3_HAS_OUT 1
#define ID_ISAR3_HAS_TRI 0
#define ID_ISAR3_IRQ_TYPE NONE
#define ID_ISAR3_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR4', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR4_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR4_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR4_COMPONENT_NAME ID_ISAR4
#define ID_ISAR4_BASE 0x120
#define ID_ISAR4_SPAN 16
#define ID_ISAR4_END 0x12f
#define ID_ISAR4_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR4_CAPTURE 0
#define ID_ISAR4_DATA_WIDTH 32
#define ID_ISAR4_DO_TEST_BENCH_WIRING 0
#define ID_ISAR4_DRIVEN_SIM_VALUE 0
#define ID_ISAR4_EDGE_TYPE NONE
#define ID_ISAR4_FREQ 50000000
#define ID_ISAR4_HAS_IN 0
#define ID_ISAR4_HAS_OUT 1
#define ID_ISAR4_HAS_TRI 0
#define ID_ISAR4_IRQ_TYPE NONE
#define ID_ISAR4_RESET_VALUE 0

/*
 * Macros for device 'ID_ISAR5', class 'altera_avalon_pio'
 * The macros are prefixed with 'ID_ISAR5_'.
 * The prefix is the slave descriptor.
 */
#define ID_ISAR5_COMPONENT_TYPE altera_avalon_pio
#define ID_ISAR5_COMPONENT_NAME ID_ISAR5
#define ID_ISAR5_BASE 0x130
#define ID_ISAR5_SPAN 16
#define ID_ISAR5_END 0x13f
#define ID_ISAR5_BIT_CLEARING_EDGE_REGISTER 0
#define ID_ISAR5_BIT_MODIFYING_OUTPUT_REGISTER 0
#define ID_ISAR5_CAPTURE 0
#define ID_ISAR5_DATA_WIDTH 32
#define ID_ISAR5_DO_TEST_BENCH_WIRING 0
#define ID_ISAR5_DRIVEN_SIM_VALUE 0
#define ID_ISAR5_EDGE_TYPE NONE
#define ID_ISAR5_FREQ 50000000
#define ID_ISAR5_HAS_IN 0
#define ID_ISAR5_HAS_OUT 1
#define ID_ISAR5_HAS_TRI 0
#define ID_ISAR5_IRQ_TYPE NONE
#define ID_ISAR5_RESET_VALUE 0

/*
 * Macros for device 'CCSIDR', class 'altera_avalon_pio'
 * The macros are prefixed with 'CCSIDR_'.
 * The prefix is the slave descriptor.
 */
#define CCSIDR_COMPONENT_TYPE altera_avalon_pio
#define CCSIDR_COMPONENT_NAME CCSIDR
#define CCSIDR_BASE 0x140
#define CCSIDR_SPAN 16
#define CCSIDR_END 0x14f
#define CCSIDR_BIT_CLEARING_EDGE_REGISTER 0
#define CCSIDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CCSIDR_CAPTURE 0
#define CCSIDR_DATA_WIDTH 32
#define CCSIDR_DO_TEST_BENCH_WIRING 0
#define CCSIDR_DRIVEN_SIM_VALUE 0
#define CCSIDR_EDGE_TYPE NONE
#define CCSIDR_FREQ 50000000
#define CCSIDR_HAS_IN 0
#define CCSIDR_HAS_OUT 1
#define CCSIDR_HAS_TRI 0
#define CCSIDR_IRQ_TYPE NONE
#define CCSIDR_RESET_VALUE 0

/*
 * Macros for device 'CLIDR', class 'altera_avalon_pio'
 * The macros are prefixed with 'CLIDR_'.
 * The prefix is the slave descriptor.
 */
#define CLIDR_COMPONENT_TYPE altera_avalon_pio
#define CLIDR_COMPONENT_NAME CLIDR
#define CLIDR_BASE 0x150
#define CLIDR_SPAN 16
#define CLIDR_END 0x15f
#define CLIDR_BIT_CLEARING_EDGE_REGISTER 0
#define CLIDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CLIDR_CAPTURE 0
#define CLIDR_DATA_WIDTH 32
#define CLIDR_DO_TEST_BENCH_WIRING 0
#define CLIDR_DRIVEN_SIM_VALUE 0
#define CLIDR_EDGE_TYPE NONE
#define CLIDR_FREQ 50000000
#define CLIDR_HAS_IN 0
#define CLIDR_HAS_OUT 1
#define CLIDR_HAS_TRI 0
#define CLIDR_IRQ_TYPE NONE
#define CLIDR_RESET_VALUE 0

/*
 * Macros for device 'AIDR', class 'altera_avalon_pio'
 * The macros are prefixed with 'AIDR_'.
 * The prefix is the slave descriptor.
 */
#define AIDR_COMPONENT_TYPE altera_avalon_pio
#define AIDR_COMPONENT_NAME AIDR
#define AIDR_BASE 0x160
#define AIDR_SPAN 16
#define AIDR_END 0x16f
#define AIDR_BIT_CLEARING_EDGE_REGISTER 0
#define AIDR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define AIDR_CAPTURE 0
#define AIDR_DATA_WIDTH 32
#define AIDR_DO_TEST_BENCH_WIRING 0
#define AIDR_DRIVEN_SIM_VALUE 0
#define AIDR_EDGE_TYPE NONE
#define AIDR_FREQ 50000000
#define AIDR_HAS_IN 0
#define AIDR_HAS_OUT 1
#define AIDR_HAS_TRI 0
#define AIDR_IRQ_TYPE NONE
#define AIDR_RESET_VALUE 0

/*
 * Macros for device 'CSSELR', class 'altera_avalon_pio'
 * The macros are prefixed with 'CSSELR_'.
 * The prefix is the slave descriptor.
 */
#define CSSELR_COMPONENT_TYPE altera_avalon_pio
#define CSSELR_COMPONENT_NAME CSSELR
#define CSSELR_BASE 0x170
#define CSSELR_SPAN 16
#define CSSELR_END 0x17f
#define CSSELR_BIT_CLEARING_EDGE_REGISTER 0
#define CSSELR_BIT_MODIFYING_OUTPUT_REGISTER 0
#define CSSELR_CAPTURE 0
#define CSSELR_DATA_WIDTH 32
#define CSSELR_DO_TEST_BENCH_WIRING 0
#define CSSELR_DRIVEN_SIM_VALUE 0
#define CSSELR_EDGE_TYPE NONE
#define CSSELR_FREQ 50000000
#define CSSELR_HAS_IN 0
#define CSSELR_HAS_OUT 1
#define CSSELR_HAS_TRI 0
#define CSSELR_IRQ_TYPE NONE
#define CSSELR_RESET_VALUE 0


#endif /* _ALTERA_CPUID_REGBRIDGE_H_ */
